# Redirection du trafic HTTP (IPv4 et IPv6) vers HTTPS
<VirtualHost *:80 [::]:80>
    ServerName medo-louis.bts-sio.eu
    Redirect permanent / https://medo-louis.bts-sio.eu/
</VirtualHost>

# Configuration du site sécurisé HTTPS (IPv4 et IPv6)
<VirtualHost *:443 [::]:443>
    ServerName medo-louis.bts-sio.eu
    DocumentRoot /var/www/portfolio_medo-louis

    # Configuration cryptographique (Certificat Wildcard)
    SSLEngine on
    SSLCertificateFile /etc/letsencrypt/live/bts-sio.eu/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/bts-sio.eu/privkey.pem

    # Sécurisation du répertoire
    <Directory /var/www/portfolio_medo-louis>
        Options -Indexes +FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>

    # Traçabilité et audit
    ErrorLog ${APACHE_LOG_DIR}/medo-louis_error.log
    CustomLog ${APACHE_LOG_DIR}/medo-louis_access.log combined
</VirtualHost>